### ISSUE TITLE
[Errno 13] Permission denied in open(path, 'rt')

### ISSUE THREAD

**Issue by blogcraft** [AbdulSheikh/Spider#8]
When running the splider in Windows 10 I get this error.
```
Traceback (most recent call last):
  File "c:\Users\blog_\Desktop\crawler\main.py", line 15, in <module>
    Spider(PROJECT_NAME, HOMEPAGE, DOMAIN_NAME)
  File "c:\Users\blog_\Desktop\crawler\spider.py", line 22, in __init__
    self.boot()
  File "c:\Users\blog_\Desktop\crawler\spider.py", line 30, in boot
    Spider.crawled = file_to_set(Spider.project_name)
  File "c:\Users\blog_\Desktop\crawler\general.py", line 31, in file_to_set
    with open(path, 'rt') as f:
PermissionError: [Errno 13] Permission denied 'PROJECT_NAME'
```
Any ideas?

**Comment by AbdulSheikh** [comment]
Run it as admin or run it with  elevated permission.
